services:
  swagger-ui:
    #build: .
    image: frigateswagger:latest
    environment:
      - SERVER_URL=http://192.168.236.238:5000
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    container_name: frigate-swagger-ui
    restart: unless-stopped
